import type { IdeaSubmission } from '@/types/domain-models';
import { IDEA_STATUS } from '@/constants/ideaStatus';

export const mockIdeaSubmissions: IdeaSubmission[] = [
  {
    id: 'mock-idea-1',
    title: 'AI Customer Service Bot',
    businessObjectives: 'Reduce average call handle time by 30% and improve first-contact resolution by automating tier-1 support queries for the customer service team.',
    intendedUserRoles: 'Customer Service Agents, Contact Center Supervisors',
    dataSources: 'CRM (Dynamics 365), Knowledge Base articles, Service ticket history',
    phiRequired: false,
    expectedOutcomes: 'Agents receive real-time AI-generated response suggestions. Supervisors see a reduction in escalations. Customer satisfaction scores improve by 15%.',
    riskFactors: 'Risk of incorrect AI suggestions leading to customer misinformation. Requires robust human-in-the-loop override mechanism.',
    status: IDEA_STATUS.DRAFT,
    department: 'Customer Experience',
    submittedBy: 'user-mock-1',
    createdOn: '2026-05-01',
  },
  {
    id: 'mock-idea-2',
    title: 'AI Expense Report Automation',
    businessObjectives: 'Eliminate manual data entry for expense reports by using AI to extract line items from receipts and pre-populate the expense form.',
    intendedUserRoles: 'All employees, Finance team approvers',
    dataSources: 'Email attachments, Mobile camera uploads, ERP system',
    phiRequired: false,
    expectedOutcomes: 'Reduce expense report processing time from 20 minutes to 3 minutes per submission. Decrease manual entry errors by 80%.',
    riskFactors: 'OCR accuracy on low-quality receipt images. Policy compliance enforcement must remain with human approvers.',
    status: IDEA_STATUS.SUBMITTED,
    department: 'Finance',
    normalizedDepartments: ['Finance'],
    submittedBy: 'user-mock-1',
    createdOn: '2026-05-05',
  },
  {
    id: 'mock-idea-3',
    title: 'AI Contract Analysis Agent',
    businessObjectives: 'Accelerate contract review cycles by having an AI agent identify non-standard clauses, flag risk terms, and summarize obligations before legal review.',
    intendedUserRoles: 'Legal Counsel, Procurement Officers, Contract Managers',
    dataSources: 'SharePoint contract library, Legal clause database',
    phiRequired: false,
    expectedOutcomes: 'Reduce contract review time by 50%. Provide structured risk summary to legal reviewers within minutes of upload.',
    riskFactors: 'Legal liability if AI misclassifies a high-risk clause. Must be advisory only — no autonomous approval or signing.',
    status: IDEA_STATUS.UNDER_REVIEW,
    department: 'Legal',
    normalizedDepartments: ['Legal', 'Procurement'],
    submittedBy: 'user-mock-1',
    createdOn: '2026-04-20',
  },
  {
    id: 'mock-idea-4',
    title: 'AI New Employee Onboarding Assistant',
    businessObjectives: 'Create a conversational agent that guides new hires through their first 90 days, answering HR policy questions, scheduling orientation sessions, and surfacing relevant learning content.',
    intendedUserRoles: 'New Hires, HR Business Partners, IT Onboarding team',
    dataSources: 'HR policy documents, SharePoint intranet, Learning Management System, Active Directory',
    phiRequired: false,
    expectedOutcomes: 'New hire time-to-productivity reduced by 2 weeks. HR ticket volume for onboarding questions reduced by 40%.',
    riskFactors: 'Accuracy of HR policy answers must be maintained as policies change. Requires clear escalation path to HR for complex queries.',
    status: IDEA_STATUS.APPROVED,
    department: 'Human Resources',
    normalizedDepartments: ['Human Resources'],
    submittedBy: 'user-mock-1',
    createdOn: '2026-03-15',
  },
  {
    id: 'mock-idea-5',
    title: 'AI Social Media Brand Monitor',
    businessObjectives: 'Monitor public social media channels for brand mentions, sentiment shifts, and emerging PR risks in real time using an agentic AI pipeline.',
    intendedUserRoles: 'Marketing team, PR & Communications, Executive team',
    dataSources: 'Public social media APIs (Twitter/X, LinkedIn, Reddit)',
    phiRequired: false,
    expectedOutcomes: 'Real-time brand sentiment dashboard. Automatic alerts for negative sentiment spikes. Reduces manual monitoring hours by 20 per week.',
    riskFactors: 'External API terms of service compliance. Risk of false-positive crisis alerts causing unnecessary escalations.',
    status: IDEA_STATUS.REJECTED,
    department: 'Marketing',
    submittedBy: 'user-mock-2',
    createdOn: '2026-04-01',
  },
  {
    id: 'mock-idea-6',
    title: 'AI Procurement Demand Forecasting',
    businessObjectives: 'Use historical purchase data and external signals to predict procurement needs 6 months in advance and automatically generate draft purchase orders.',
    intendedUserRoles: 'Procurement Managers, Supply Chain Analysts, Finance Controllers',
    dataSources: 'ERP purchase history, External commodity price feeds, Inventory management system',
    phiRequired: false,
    expectedOutcomes: 'Reduce stockout incidents by 25%. Lower emergency procurement spend by 15% annually.',
    riskFactors: 'Model accuracy dependent on data quality and completeness of historical ERP records. Pending data governance review.',
    status: IDEA_STATUS.ON_HOLD,
    department: 'Procurement',
    submittedBy: 'user-mock-2',
    createdOn: '2026-03-28',
  },
  {
    id: 'mock-idea-7',
    title: 'AI HR Policy Q&A Agent',
    businessObjectives: 'Deploy a Teams-integrated agent that answers employee HR policy questions instantly, reducing HR helpdesk ticket volume for routine queries.',
    intendedUserRoles: 'All employees, HR Helpdesk team',
    dataSources: 'HR policy SharePoint, Employee handbook, Benefits documentation',
    phiRequired: false,
    expectedOutcomes: 'Deflect 60% of tier-1 HR queries. HR team focus shifts to complex case work. 24/7 availability for policy questions.',
    riskFactors: 'Policy documents must be kept current. Regulatory compliance risk if outdated policy is cited.',
    status: IDEA_STATUS.IN_PROGRESS,
    department: 'Human Resources',
    normalizedDepartments: ['Human Resources'],
    submittedBy: 'user-mock-2',
    createdOn: '2026-02-10',
  },
  {
    id: 'mock-idea-8',
    title: 'AI Invoice Processing',
    businessObjectives: 'Automate end-to-end accounts payable invoice processing using AI to extract, validate, and route invoices through the approval workflow.',
    intendedUserRoles: 'Accounts Payable team, Finance Managers, Vendors',
    dataSources: 'Email inbox (AP mailbox), ERP vendor master, Purchase order database',
    phiRequired: false,
    expectedOutcomes: 'Process 90% of standard invoices without human touch. Reduce processing cost per invoice by 60%. Eliminate late-payment penalties.',
    riskFactors: 'Fraud detection must remain human-reviewed. Vendor master data quality is a prerequisite.',
    status: IDEA_STATUS.COMPLETED,
    department: 'Finance',
    normalizedDepartments: ['Finance', 'Procurement'],
    submittedBy: 'user-mock-2',
    createdOn: '2026-01-15',
  },
];
