import type { LookupOption } from '@/types/domain-models';

export const mockLookupOptions: LookupOption[] = [
  {
    id: 'lkp-obj-1',
    category: 'business-objectives',
    name: 'Reduce Cycle Time',
    description: 'Shorten end-to-end process duration for key workflows.',
    isActive: true,
  },
  {
    id: 'lkp-obj-2',
    category: 'business-objectives',
    name: 'Increase Quality',
    description: 'Improve outcome quality and reduce defects or rework.',
    isActive: true,
  },
  {
    id: 'lkp-role-1',
    category: 'intended-user-roles',
    name: 'CoE Analysts',
    description: 'AI CoE analysts and reviewers.',
    isActive: true,
  },
  {
    id: 'lkp-role-2',
    category: 'intended-user-roles',
    name: 'Department Managers',
    description: 'Business approvers and process owners.',
    isActive: true,
  },
  {
    id: 'lkp-ds-1',
    category: 'data-sources',
    name: 'Dataverse',
    description: 'Core business data in Dataverse tables.',
    isActive: true,
  },
  {
    id: 'lkp-ds-2',
    category: 'data-sources',
    name: 'SharePoint',
    description: 'Documents and list content hosted in SharePoint.',
    isActive: true,
  },
  {
    id: 'lkp-out-1',
    category: 'expected-outcomes',
    name: 'Time Savings',
    description: 'Reduce effort required for targeted tasks.',
    isActive: true,
  },
  {
    id: 'lkp-out-2',
    category: 'expected-outcomes',
    name: 'Cost Reduction',
    description: 'Lower operational spend for the target process.',
    isActive: true,
  },
  {
    id: 'lkp-risk-1',
    category: 'risk-factors',
    name: 'Data Privacy',
    description: 'Potential exposure of sensitive or regulated data.',
    isActive: true,
  },
  {
    id: 'lkp-risk-2',
    category: 'risk-factors',
    name: 'Model Accuracy',
    description: 'Risk from incorrect or low-confidence model outputs.',
    isActive: true,
  },
  {
    id: 'lkp-dept-1',
    category: 'departments',
    name: 'Finance',
    description: 'Finance organization use cases.',
    isActive: true,
  },
  {
    id: 'lkp-dept-2',
    category: 'departments',
    name: 'Human Resources',
    description: 'HR and people operations use cases.',
    isActive: true,
  },
  // AI CoE Roles
  {
    id: 'lkp-coe-role-1',
    category: 'ai-coe-roles',
    name: 'CoE Lead',
    description: 'Leads the AI CoE program and final approval authority.',
    isActive: true,
  },
  {
    id: 'lkp-coe-role-2',
    category: 'ai-coe-roles',
    name: 'Technical Reviewer',
    description: 'Evaluates technical feasibility and architectural fit.',
    isActive: true,
  },
  {
    id: 'lkp-coe-role-3',
    category: 'ai-coe-roles',
    name: 'Business Analyst',
    description: 'Assesses business value, ROI, and process impact.',
    isActive: true,
  },
  {
    id: 'lkp-coe-role-4',
    category: 'ai-coe-roles',
    name: 'Security Reviewer',
    description: 'Evaluates data security, privacy, and compliance risks.',
    isActive: true,
  },
  {
    id: 'lkp-coe-role-5',
    category: 'ai-coe-roles',
    name: 'Ethics & Responsible AI',
    description: 'Reviews proposals for responsible AI alignment and bias risk.',
    isActive: true,
  },
  {
    id: 'lkp-coe-role-6',
    category: 'ai-coe-roles',
    name: 'Executive Sponsor',
    description: 'Provides executive sign-off for approved proposals.',
    isActive: true,
  },
];
